site_name: Feedbax
site_author: Matt Laporte 
site_url: https://docs.lprt.ca/feedbax 

repo_url: https://github.com/mlprt/feedbax
repo_name: mlprt/feedbax

theme:
  name: material 
  features:
    - navigation.sections 
    - toc.integrate
    - header.autohide
  icon:
    logo: "material/arm-flex"  #rotate-left, directory-sync, all-inclusive

markdown_extensions:
  - pymdownx.arithmatex:  # Render LaTeX via MathJax
      generic: true
  - pymdownx.superfences  # Enables syntax highlighting
  # codehilite (mknotebooks) and pymdownx.highlight (material) actually don't work for highlighting
  - admonition
  
extra_css:
  - _static/custom.css
  
extra_javascript:
  - _static/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search 
  - mknotebooks:  # Jupyter notebooks
      # write_markdown: true  # Write markdown files for notebooks
  - mkdocstrings:
      handlers:
          python: 
              options:
                  heading_level: 4  # Heading level for the object name 
                  show_root_heading: true  # Show the object name 
                  show_root_full_path: true  # Show the full path of the object
                  show_source: false
                  members_order: source  # Same member ordering as in source code
                  

nav:
  - 'index.md'
  - Examples:
      - TestNB: 'tmp/8c_pm_simple_xabdeef_hi.ipynb'
    
  