[build-system]
requires = [
    "setuptools>=61",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "feedbax"
version = "0.0.1"
description = "Optimal feedback control in JAX."
# url = ""
authors = [
    {name = "Matt L Laporte", email = "matt.l.laporte@gmail.com"}
]
license = {text = "Apache 2.0"}
readme = "README.md"
keywords = [
    'optimal control',
    'optimal feedback control',
    'pytorch',
    'biomechanics'
]
requires-python = ">=3.10.6"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "diffrax",
    "equinox",
    "jax",
    "jaxtyping",
    "matplotlib",
    "numpy",
    "optax",
    "seaborn",
    "tqdm",
]

[project.urls]
# homepage = ""
# documentation = ""
# repository = ""

[project.optional-dependencies]
analysis = [
    'pandas',
]
tensorboard = [
    'tensorboardX',
    'crc32c',
]
typing = [
    'mypy',
    'typeguard',
]
tests = [
    'coverage',
    'pytest',
]

[tool.setuptools]
py-modules = ["feedbax"]

[tool.black]


